### ISSUE TITLE
Unable to install glsp locally

### ISSUE THREAD

**Issue by CaspianA1** [fleabitdev/glsp#13]
I'll admit that I'm not too familiar with rust - and I have tried these two ways to install glsp:
-  cargo install glsp
-  cargo build (with a Cargo.toml file that looks like this: glsp = "0.1.0")
How do I install it?

**Comment by fleabitdev** [comment]
`glsp` is a library, rather than an executable program.

Rust programs almost always use the Cargo package manager, and with Cargo there's no need to explicitly install libraries like `glsp`. You simply list them in your `Cargo.toml` file, and they're automatically downloaded and compiled when you compile your Rust program. The [Cargo Book](https://doc.rust-lang.org/cargo/index.html) has the details.

This means that your second option (`cargo build` with `glsp = "0.1.0"`) should have worked. What problems are you encountering?

**Comment by CaspianA1** [comment]
By the way I figured it out now - I had to setup a standard cargo project, and additionally I had to add this to the first line of my main.rs file: 'extern crate glsp;'. I'm not sure why this solved it, but I'm thinking that knowing this might be helpful for anyone struggling with this.

**Comment by CaspianA1** [comment]
![Uploading 88064549...]()
