### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by CaspianA1** [fleabitdev/glsp#14]
When I copy the "tennis.glsp" code from the GameLisp playground into a "main.glsp" file and build and run the project, nothing shows up on screen. Is there anything extra that I need to do to my "main.rs" file?

```
extern crate glsp;
use glsp::prelude::*;

fn main() {
    let runtime = Runtime::new();
    runtime.run(|| {
        glsp::load("main.glsp")?;
        Ok(())
    });
}
```

**Comment by fleabitdev** [comment]
`tennis.glsp` is written against a game engine which is only provided by the playground webpage, and which can't be used anywhere else. The `glsp` crate doesn't come with a built-in game engine at all.

There are currently no ready-made game engine binding crates available, so in order to use GameLisp to script a game engine (or to do anything other than printing text to the screen!), you'd need to write the Rust bindings yourself. [Section 2](https://gamelisp.rs/reference/the-rust-api.html) of the Reference Manual describes how to call Rust functions and manipulate Rust types from GameLisp.

You mentioned in a previous issue that you're relatively unfamiliar with Rust, so I should mention that GameLisp's Rust API makes  heavy use of more-advanced Rust features like auto traits, macros, and interior mutability. You might want to spend some time working with other Rust libraries first.

**Comment by CaspianA1** [comment]
Got it, thanks
