### ISSUE TITLE
rdata! as a derive attribute

### ISSUE THREAD

**Issue by tversteeg** [fleabitdev/glsp#2]
Wouldn't it be cleaner and more Rust-like to make the `rdata!` macro a derive attribute?

You would get

```rust
#[derive(Rdata)]
struct ...
```

instead of 

```rust
rdata! {
	struct ...
}
```

Or is this not possible?

Awesome project btw!

**Comment by fleabitdev** [comment]
The main trade-off today is that we would lose the syntactic sugar for associating methods and properties with an `RStore` type:

    rdata! {
        struct Frob;

        meths {
            get "nicate": Frob::nicate
        }
    }

It would also make it difficult to add more features to `rdata!` in the future. For example, we might eventually want `rdata!` to accept an explicit classname, or a constructor, or state names, or `impl` blocks...

Finally, the derive macro would have to be `#[derive(RStore)]` rather than `#[derive(RData)]`, which might be counterintuitive.

> Awesome project btw!

Thanks :)

**Comment by tversteeg** [comment]
Thanks for the quick response. I understand the problem.

Would there be a downside to having both the macro and the attribute?

Or maybe having attributes like Serde could be another option, they put a lot of extra options there: https://serde.rs/attributes.html

**Comment by fleabitdev** [comment]
In general, I'd prefer to avoid having two ways to achieve the same thing - it makes the language less teachable.

Serde's use of attributes is great, but attributes within a `#[derive]` macro can only be applied to fields, not methods. Something like this would be an option, but I personally find it uglier than the status quo:

    #[derive(RStore)]
    #[getter("nicate", Frob::nicate)]
    struct Frob;

I'd also like to avoid pulling in `syn` as a dependency. This means that `rdata` ideally needs to stay as a `macro_rules!` macro, rather than a procedural macro.

In the end, wrapping declarations in a macro feels pretty Rust-like to me in any case. A similar pattern is used by macros like `lazy_static!`, `bitflags!`, `thread_local!` and `rental!`.

**Comment by tversteeg** [comment]
Those are all good arguments!
